media:
  input: public
  output: /
content:
  - name: paintings
    label: Paintings
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: cover, label: Cover Image, type: image}

  - name: collages
    label: Collages
    type: collection
    path: src/content/collages
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: cover, label: Cover Image, type: image}
  - name: tattoo
    label: Tattoo
    type: collection
    path: src/content/tattoo
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: cover, label: Cover Image, type: image}
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
